### ISSUE TITLE
Mod directory to json

### ISSUE THREAD

**Issue by knightmar** [zuygui/flowupdater-json-creator#11]
Hi, I think an interesting feature would be to be able to specify a folder containing the mods to be used, and have the software manage to create the json from the jar files in the folder.

**Comment by zuygui** [comment]
The problem is how to be sure the base url link is sure ?
If you found a solution, you can open an **Pull Request** where you added this on the TODO.

Cordialy

**Comment by knightmar** [comment]
Hi, how's it going? I'm still using flow's json creator but I'd really like to turn to your solution when this feature becomes available.

**Comment by zuygui** [comment]
Oh sorry ! I'm so sorry ! I forgot to implement the feature because I have some courses to learn for school 😅. I'll work on that when I can't. Thank you for keeping me !

**Comment by zuygui** [comment]
It's done, you can found the release [here](https://github.com/zuygui/flowupdater-json-creator/releases/tag/cli-1.5.0)
